# Generated by Django 4.0.3 on 2023-07-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
