# Generated by Django 4.0.3 on 2023-07-26 01:25

from django.db import migrations


def generate_employee_ids(apps, schema_editor):
    Technician = apps.get_model('service_rest', 'Technician')
    for technician in Technician.objects.all():
        technician.employee_id = f"{technician.first_name[0].lower()}.{technician.last_name.lower()}"
        technician.save()


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_technician_employee_id'),
    ]

    operations = [
        migrations.RunPython(generate_employee_ids)
    ]
