# Generated by Django 4.0.3 on 2023-07-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_auto_20230726_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='VIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
