# Generated by Django 4.0.3 on 2023-07-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_vip_alter_automobilevo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='VIP',
            new_name='vip',
        ),
    ]
